name: Price Drop Alert CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # - name: Run Lint
      #   run: npm run lint

      # - name: Run Tests
      #   run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - name: Deploy to AWS EC2
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
            cd $DEPLOY_PATH &&
            git pull origin main &&
            npm install &&
            pm2 restart all
          "

  notify:
  needs: deploy
  runs-on: ubuntu-latest
  if: always()  
  env:
    LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
    LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
  steps:
    - name: 設定通知訊息
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          MESSAGE="✅ CI/CD 成功！\nRepo: ${{ github.repository }}\nCommit: ${{ github.sha }}"
        else
          MESSAGE="❌ CI/CD 失敗，請檢查！\nRepo: ${{ github.repository }}"
        fi

        curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $LINE_CHANNEL_ACCESS_TOKEN" \
          -d "{
              \"to\": \"$LINE_USER_ID\",
              \"messages\":[
                  {
                      \"type\":\"text\",
                      \"text\":\"$MESSAGE\"
                  }
              ]
          }"
